name: Build and Push Assets to Staging server

on: 
  push: 
    branches: [ main ]

  workflow_dispatch:

jobs:
    build:
      name: "Deploy to staging"
      runs-on: ubuntu-latest
      steps: 
        - name: Checkout Commit
          uses: actions/checkout@v2
        
        - name: Use Node.js 14.x
          uses: actions/setup-node@v1
          with:
            materix: 
            node-version: 14.x
        
        - name: Bootstraping packages
          run: yarn install
        
        - name: run gh-dist
          run: |
            yarn gh-dist

        - name: Run create dist.tar
          run: |
            mkdir ../build
            cp -TR . ../build
            tar -cvf dist.tar ../build/


        # - name: copy file via ssh password
        #   uses: appleboy/scp-action@master
        #   with:
        #     host: ${{ secrets.STAGING_HOST }}
        #     username: ${{ secrets.STAGING_USER }}
        #     key: ${{ secrets.STAGING_KEY }}
        #     source: "deploy.tar"
        #     target: "destination/folder"
        
        # - name: executing remote ssh commands using password
        #   uses: appleboy/ssh-action@master
        #   with:
        #     host: ${{ secrets.STAGING_HOST }}
        #     username: ${{ secrets.STAGING_USER }}
        #     key: ${{ secrets.STAGING_KEY }}
        #     script: |
        #       bash ~/frontscripts-dep.sh



